In [1]:
import pandas as pd

In [36]:
df = pd.read_csv('../test_data_1/peru_export_combined_data_1.csv')

In [3]:
columns = list(df.columns)

In [4]:
columns.remove('PanjivaRecordID')

In [5]:
columns

['ShipperCountry',
 'ShipperPanjivaID',
 'ShipmentDestination',
 'PortOfUnladingUNLOCODE',
 'TransportMethod',
 'hscode_6',
 'CustomsCode',
 'LocationCode']

In [27]:
# df['Count'] = df.groupby(columns)['PanjivaRecordID'].transform('count')
df_collated = df.groupby(columns).count().reset_index()
del df_collated['PanjivaRecordID']
del df_collated['Count']

In [39]:
del df_collated['PanjivaRecordID']
del df_collated['Count']

In [41]:
# df_1 = df.sort_values(by=['Count'],ascending=False)

In [42]:
df_1

,PanjivaRecordID,ShipperCountry,ShipperPanjivaID,ShipmentDestination,PortOfUnladingUNLOCODE,TransportMethod,hscode_6,CustomsCode,LocationCode,Count
3298,8713000,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
34038,9119795,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
4932,7011231,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
19793,6116678,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
33159,9119772,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
30209,5982779,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
16712,5465520,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
16714,5517936,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
31127,5386770,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
11988,9418036,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
28689,8884330,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
19787,6150726,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
16724,5465829,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
31126,5413202,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
19778,6090570,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
13053,5139604,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
19775,6116682,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
11990,9418060,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
4913,6903949,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
36835,9182002,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
31113,5386782,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
11991,9418072,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
19764,6150730,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
2474,6317954,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
2476,6418697,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
9721,6593513,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
33841,9119783,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
2407,6444602,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
24502,8531339,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
19837,6224961,Peru,33448016.0,United States,USMIA,Air,442090,235,150122.0,3056
...,...,...,...,...,...,...,...,...,...,...
8175,5954823,Peru,28769918.0,Netherlands,NLRTM,Maritime,440929,118,150122.0,1
4664,7038634,Peru,37660499.0,Spain,ESMAD,Air,442010,235,150122.0,1
43722,7225690,Peru,36743221.0,United States,USLFT,Maritime,441900,118,150132.0,1
8158,6227850,Peru,18803382.0,Bahamas,BSNAS,Maritime,442190,118,150134.0,1
2804,8835487,Peru,23390916.0,France,FRMTX,Maritime,440929,118,250203.0,1
28869,8905950,Peru,38623106.0,Germany,DELEJ,Air,442010,235,70106.0,1
12719,5189864,Peru,28395846.0,United States,USHOU,Maritime,940161,118,150118.0,1
43716,7338591,Peru,39231324.0,Colombia,COBOG,Air,442090,235,70102.0,1
8192,5991111,Peru,28769918.0,United States,USDAC,Maritime,441879,118,150122.0,1
19839,6107457,Peru,23138488.0,United States,US-UNKNOWN,Air,442010,235,150103.0,1
12664,5218362,Peru,45868096.0,United States,USJKV,Air,441400,235,150140.0,1
8211,6019758,Peru,23118866.0,United States,USMIA,Air,442090,235,150132.0,1
22930,7842698,Peru,38273439.0,Antigua And Barbuda,AGBBQ,Air,442190,235,150111.0,1
8278,5972903,Peru,34267225.0,Panama,PAPTY,Air,441400,235,150133.0,1
13803,8451301,Peru,28286158.0,United States,USBAL,Maritime,442090,118,220900.0,1
25957,5841764,Peru,36298144.0,Switzerland,GBGIR,Air,441900,235,150140.0,1
21860,7886359,Peru,28745080.0,Cuba,CUHAV,Air,442010,235,150119.0,1
35542,6703534,Peru,45160218.0,Chile,CLARI,Truck,442190,172,150101.0,1
27469,8360019,Peru,1019548.0,United States,USMIA,Air,940360,235,150101.0,1
8259,6006615,Peru,23390916.0,Panama,HRPLE,Maritime,440929,118,70101.0,1
25963,5839460,Peru,1441481.0,Colombia,COBOG,Air,442010,235,150122.0,1
43749,6834815,Peru,38709986.0,Netherlands,NLRTM,Maritime,441520,118,150103.0,1
22909,7800868,Peru,28589232.0,Italy,ITMXP,Air,442010,235,150117.0,1
25968,5913636,Peru,23390916.0,France,FRBAS,Maritime,440929,118,150119.0,1
8249,6015319,Peru,28287973.0,United States,USHOU,River,440722,226,160106.0,1
38492,6912731,Peru,23390916.0,Germany,DKCPH,Maritime,440929,118,70101.0,1
33319,9125676,Peru,35429251.0,Panama,PAPTY,Air,442090,235,150132.0,1
33798,9193957,Peru,23390916.0,Australia,AUBRA,Maritime,440799,118,150101.0,1
42276,7983885,Peru,45121240.0,Costa Rica,CRSJO,Maritime,442190,118,150110.0,1
29852,8176751,Peru,37404368.0,Japan,JPNRT,Air,441400,235,150121.0,1

In [37]:
df['hscode_6'] = df['hscode_6'].astype(str)
df['LocationCode'] = df['LocationCode'].astype(str)
df['CustomsCode'] = df['CustomsCode'].astype(str)

for i,row in df_collated.iterrows():
    q_str =[]
    for j in columns:
        q_str.append(' {} == "{}" '.format (j, row[j]))
            
    q_str= ' and '.join(q_str)
    print(q_str)
    z = df.query(q_str)
    print(z)
    break

 ShipperCountry == "Peru"  and  ShipperPanjivaID == "1019548.0"  and  ShipmentDestination == "Brazil"  and  PortOfUnladingUNLOCODE == "BRCWB"  and  TransportMethod == "Air"  and  hscode_6 == "442010"  and  CustomsCode == "235"  and  LocationCode == "150101.0"
      PanjivaRecordID ShipperCountry  ShipperPanjivaID ShipmentDestination  \
2179          6521333           Peru         1019548.0              Brazil
2272          6554345           Peru         1019548.0              Brazil

     PortOfUnladingUNLOCODE TransportMethod hscode_6 CustomsCode LocationCode
2179                  BRCWB             Air   442010         235     150101.0
2272                  BRCWB             Air   442010         235     150101.0